version: "3"
services:
  web-service:
    image: yokeandsong/eureka-server:part2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 700M
      restart_policy:
        condition: on-failure
    ports:
    - "8761:8761"
    networks:
    - my-net
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - my-net
