eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  ignored-services: "*"
  routes:
    web-item-service:
      path: /view/**
      service-id: web-view-service
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
    web-shop-cart-service:
      path: /cart/**
      service-id: web-shop-cart-service
    member-service:
      path: /member/**
      service-id: member-service
      strip-prefix: false

spring:
  profiles:
    active: dev