eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
zuul:
  routes:
    api-item:
      path: /item/**
      serviceId: web-app
    api-user:
      path: /user/**
      serviceId: manager-app
