db:
  server: www.test.com
  port: 13306
  username: root
  password: ${common.password}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    host: www.test.com
    password: ${common.password}

common:
  password: "FJEOIRFWQ132EW"
# rabbitmq config
item:
  exchange: item_exchange
  vary_key: item_vary.key
  queue: item_queue
  routing-key: item_vary.*